import { useState,type FormEvent } from 'react';
import { AppShell,type AppSection } from '../../../components/layout';
import { Button } from '../../../components/ui';
import type { OnboardingProfile } from '../../onboarding';
import { CARDIO_CATEGORIES,CARDIO_CATEGORY_LABELS,cardioDurationTierXp,cardioMinimumMinutes,validateCardioLogInput,type CardioCategory,type CardioLogInput,type CardioSnapshot } from '../model';
import styles from './CardioScreen.module.css';
function duration(seconds:number){const minutes=Math.round(seconds/60);return minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}m`:`${minutes} min`}
function dateLabel(value:string){return new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${value}T12:00:00Z`))}
export function CardioScreen({profile,onNavigate,onSignOut,status,snapshot,error,busy,retry,log,remove}:{profile:OnboardingProfile;onNavigate:(section:AppSection)=>void;onSignOut:()=>void;status:'loading'|'ready'|'error';snapshot:CardioSnapshot|null;error:string;busy:boolean;retry:()=>Promise<unknown>;log:(input:CardioLogInput)=>Promise<boolean>;remove:(id:string)=>Promise<boolean>}){const[category,setCategory]=useState<CardioCategory>('RUNNING');const[minutes,setMinutes]=useState('20');const[notes,setNotes]=useState('');const[localError,setLocalError]=useState('');const parsed=Number(minutes);const tier=cardioDurationTierXp(category,parsed);const minimum=cardioMinimumMinutes(category);
 const submit=async(event:FormEvent)=>{event.preventDefault();const input={category,activeDurationMinutes:parsed,notes};const validation=validateCardioLogInput(input);if(validation){setLocalError(validation);return}setLocalError('');if(await log(input)){setMinutes('20');setNotes('')}};
 return <AppShell activeItem="workouts" onNavigate={onNavigate} onSignOut={onSignOut} userLabel={profile.displayName} userMeta={`@${profile.username}`}><main className={styles.page}><header className={styles.header}><div><p className={styles.kicker}>CARDIO ACCESSORY</p><h1>Log cardio</h1><p>Cardio can add a small daily bonus. It never counts as a lifting day.</p></div><Button variant="secondary" onClick={()=>onNavigate('workouts')}>Back to lifting</Button></header>
 <section className={styles.logCard}><div><p className={styles.sectionLabel}>NEW ACTIVITY</p><h2>Completed cardio</h2><p>Log active duration only. The best eligible cardio activity of the day determines the 5/10/15 XP bonus.</p></div><form className={styles.form} onSubmit={submit}><label><span>Activity</span><select value={category} onChange={e=>setCategory(e.target.value as CardioCategory)}>{CARDIO_CATEGORIES.map(c=><option key={c} value={c}>{CARDIO_CATEGORY_LABELS[c]}</option>)}</select></label><label><span>Active minutes</span><input inputMode="numeric" min="1" max="360" step="1" type="number" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><label className={styles.notes}><span>Notes <small>optional</small></span><textarea maxLength={5000} rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Easy run, pickup hockey, intervals…"/></label><div className={styles.tier}><strong>{tier>0?`+${tier} XP tier`:'Below bonus minimum'}</strong><span>{CARDIO_CATEGORY_LABELS[category]} needs at least {minimum} active minutes. Only the day’s best eligible cardio bonus is awarded.</span></div>{(localError||error)&&<p className={styles.error} role="alert">{localError||error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Log cardio'}</Button></form></section>
 {status==='loading'&&!snapshot?<div className={styles.state} role="status">Loading cardio history…</div>:status==='error'&&!snapshot?<div className={styles.state}><p>{error}</p><Button onClick={()=>void retry()}>Try again</Button></div>:snapshot&&<><section className={styles.summary} aria-label="Cardio summary"><div><span>All-time sessions</span><strong>{snapshot.summary.totalActivities}</strong></div><div><span>All-time active time</span><strong>{snapshot.summary.totalActiveMinutes} min</strong></div><div><span>Last 30 days</span><strong>{snapshot.summary.last30DaysActiveMinutes} min</strong></div><div><span>30-day cardio XP</span><strong>{snapshot.summary.last30DaysBonusXp} XP</strong></div></section><section className={styles.history}><div className={styles.sectionHeading}><p className={styles.sectionLabel}>HISTORY</p><h2>Recent cardio</h2><p>Accessory history only—these sessions do not increase weekly lifting-day consistency.</p></div>{snapshot.history.length===0?<p className={styles.empty}>No cardio logged yet.</p>:<ul>{snapshot.history.map(entry=><li key={entry.workoutId}><div><strong>{CARDIO_CATEGORY_LABELS[entry.category]}</strong><span>{dateLabel(entry.scoringDate)} · {duration(entry.activeDurationSeconds)}</span>{entry.notes&&<small>{entry.notes}</small>}</div><div className={styles.historyRight}><span className={entry.dailyBonusXp>0?styles.bonus:styles.noBonus}>{entry.dailyBonusXp>0?`+${entry.dailyBonusXp} XP daily bonus`:entry.qualifiesCardioBonus?'Eligible · another activity owns today’s bonus':'No bonus'}</span><Button aria-label={`Delete ${CARDIO_CATEGORY_LABELS[entry.category]} from ${entry.scoringDate}`} disabled={busy} variant="ghost" onClick={()=>void remove(entry.workoutId)}>Delete</Button></div></li>)}</ul>}</section></>}</main></AppShell>}
