import { useEffect,useState } from 'react';
import { AppShell,type AppSection } from '../../../components/layout';
import { Button,SelectField,TextField } from '../../../components/ui';
import type { OnboardingProfile } from '../../onboarding';
import { ProfilePicture } from '../../profile-picture';
import type { CreateGroupInput,GroupMember,GroupSummary,ManagedGroupInvite,PendingGroupInvite } from '../model';
import { CreateGroupForm } from './CreateGroupForm';
import styles from './GroupAdministrationScreen.module.css';
interface Props{
 profile:OnboardingProfile;groups:GroupSummary[];group:GroupSummary;members:GroupMember[];invites:ManagedGroupInvite[];pendingInvites:PendingGroupInvite[];error:string;busyAction:string|null;
 creatingGroup:boolean;createGroupError:string;onCreateGroup:(input:CreateGroupInput)=>Promise<unknown>|unknown;
 onNavigate:(s:AppSection)=>void;onSignOut:()=>void;onSelectGroup:(id:string)=>void;onRename:(n:string)=>Promise<unknown>;
 onCreateInvite:(recipient:string)=>Promise<unknown>;onRevokeInvite:(id:string)=>Promise<unknown>;onAcceptInvite:(id:string)=>Promise<unknown>;onDeclineInvite:(id:string)=>Promise<unknown>;
 onSetMemberRole:(id:string,r:'ADMIN'|'MEMBER')=>Promise<unknown>;onRemoveMember:(id:string)=>Promise<unknown>;onTransferOwnership:(id:string)=>Promise<unknown>;onLeaveGroup:()=>Promise<unknown>;
}
function canRemove(actor:GroupSummary['role'],target:GroupMember){if(target.role==='OWNER')return false;if(actor==='OWNER')return true;return actor==='ADMIN'&&target.role==='MEMBER';}
export function GroupAdministrationScreen(props:Props){
 const {profile,groups,group,members,invites,pendingInvites,error,busyAction,creatingGroup,createGroupError,onCreateGroup,onNavigate,onSignOut,onSelectGroup,onRename,onCreateInvite,onRevokeInvite,onAcceptInvite,onDeclineInvite,onSetMemberRole,onRemoveMember,onTransferOwnership,onLeaveGroup}=props;
 const [name,setName]=useState(group.name),[recipient,setRecipient]=useState('');useEffect(()=>setName(group.name),[group.id,group.name]);
 const canManage=group.role==='OWNER'||group.role==='ADMIN',isOwner=group.role==='OWNER';
 const inviteCode=profile.profileCode;
 return <AppShell activeItem="groups" onNavigate={onNavigate} onSignOut={onSignOut} userLabel={profile.displayName} userMeta={`@${profile.username} · ${profile.weeklyWorkoutTarget} lift days`}>
 <div className={styles.page}>
  <header className={styles.header}><div><p className={styles.kicker}>GROUPS</p><h1>{group.name}</h1><p>Manage members and invitations sent to specific people.</p>{inviteCode&&<p className={styles.inviteCode}>Your invite ID: {inviteCode}</p>}</div><div className={styles.headerActions}>{groups.length>1&&<SelectField label="Group" value={group.id} onChange={e=>onSelectGroup(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</SelectField>}<Button onClick={()=>onNavigate('compete')} variant="secondary">Open competition</Button></div></header>
  {error&&<p className={styles.error} role="alert">{error}</p>}
  {pendingInvites.length>0&&<section className={styles.section} aria-labelledby="incoming-heading"><div className={styles.sectionHeader}><div><p className={styles.sectionLabel}>For you</p><h2 id="incoming-heading">Pending invitations</h2><p>Accepting another invitation adds that group to your account without replacing your current memberships.</p></div></div><ul className={styles.inviteList}>{pendingInvites.map(i=><li className={styles.inviteRow} key={i.id}><div className={styles.inviteMeta}><strong>{i.groupName}</strong><span>From {i.invitedByDisplayName} (@{i.invitedByUsername})</span></div><div className={styles.actions}><button className={styles.actionButton} disabled={busyAction!==null} onClick={()=>void onAcceptInvite(i.id)} type="button">Accept</button><button className={styles.dangerButton} disabled={busyAction!==null} onClick={()=>void onDeclineInvite(i.id)} type="button">Decline</button></div></li>)}</ul></section>}
  <section className={styles.section} aria-labelledby="your-groups-heading"><div className={styles.sectionHeader}><div><p className={styles.sectionLabel}>Memberships</p><h2 id="your-groups-heading">Your groups</h2><p>You currently belong to {groups.length} group{groups.length===1?'':'s'}. You can join or own more than one at the same time.</p></div></div><details className={styles.createGroupDetails}><summary>Create another group</summary><div className={styles.createGroupForm}><CreateGroupForm busy={creatingGroup} error={createGroupError} onSubmit={onCreateGroup}/></div></details></section>
  <section className={styles.section} aria-labelledby="members-heading"><div className={styles.sectionHeader}><div><p className={styles.sectionLabel}>Crew</p><h2 id="members-heading">Members</h2></div><p>{members.length} active</p></div><ul className={styles.memberList}>{members.map(member=>{const self=member.userId===profile.id,busy=busyAction?.includes(member.userId)??false;return <li className={styles.memberRow} key={member.userId}><ProfilePicture displayName={member.displayName} size="sm" src={member.profilePictureUrl}/><div className={styles.identity}><strong>{member.displayName}{self?' (You)':''}</strong><span>@{member.username}</span></div><span className={styles.role}>{member.role}</span>{!self&&(isOwner||canRemove(group.role,member))&&<div className={styles.actions}>{isOwner&&member.role!=='OWNER'&&<button className={styles.actionButton} disabled={busy} onClick={()=>void onSetMemberRole(member.userId,member.role==='ADMIN'?'MEMBER':'ADMIN')} type="button">{member.role==='ADMIN'?'Make member':'Make admin'}</button>}{isOwner&&member.role!=='OWNER'&&<button className={styles.actionButton} disabled={busy} onClick={()=>void onTransferOwnership(member.userId)} type="button">Transfer ownership</button>}{canRemove(group.role,member)&&<button className={styles.dangerButton} disabled={busy} onClick={()=>void onRemoveMember(member.userId)} type="button">Remove</button>}</div>}</li>})}</ul></section>
  {canManage&&<section className={styles.section} aria-labelledby="invites-heading"><div className={styles.sectionHeader}><div><p className={styles.sectionLabel}>Access</p><h2 id="invites-heading">Invites</h2></div></div>
   <form className={styles.inviteForm} onSubmit={e=>{e.preventDefault();if(recipient.trim()){void onCreateInvite(recipient).then(()=>setRecipient(''));}}}><TextField autoCapitalize="none" autoComplete="off" hint="Enter their username or invite ID." label="Invite someone" name="groupInviteRecipient" placeholder="Username or invite ID" spellCheck={false} value={recipient} onChange={e=>setRecipient(e.target.value)}/><Button disabled={busyAction==='invite:create'||!recipient.trim()} type="submit" variant="secondary">{busyAction==='invite:create'?'Sending…':'Send invite'}</Button></form>
   {invites.length===0?<p className={styles.empty}>No pending outgoing invitations.</p>:<ul className={styles.inviteList}>{invites.map(i=><li className={styles.inviteRow} key={i.id}><div className={styles.inviteMeta}><strong>{i.invitedDisplayName}</strong><span>@{i.invitedUsername}</span></div><div className={styles.actions}><button className={styles.dangerButton} disabled={busyAction===`invite:${i.id}`} onClick={()=>void onRevokeInvite(i.id)} type="button">Revoke</button></div></li>)}</ul>}
  </section>}
  {canManage&&<section className={styles.section} aria-labelledby="group-settings-heading"><div className={styles.sectionHeader}><div><p className={styles.sectionLabel}>Settings</p><h2 id="group-settings-heading">Group name</h2></div></div><form className={styles.renameForm} onSubmit={e=>{e.preventDefault();void onRename(name);}}><TextField label="Name" maxLength={80} onChange={e=>setName(e.target.value)} value={name}/><Button disabled={busyAction==='rename'||name.trim()===group.name} type="submit" variant="secondary">Save name</Button></form></section>}
  <section className={styles.settings} aria-labelledby="membership-heading"><p className={styles.sectionLabel}>Membership</p><h2 id="membership-heading">Your place in this group</h2><p className={styles.settingsText}>{isOwner?'Owners must transfer ownership before leaving.':'Leaving removes your active membership from this group only. Your other group memberships are unchanged.'}</p><div className={styles.leaveRow}>{!isOwner&&<Button disabled={busyAction==='leave'} onClick={()=>void onLeaveGroup()} variant="ghost">Leave group</Button>}<span className={styles.leaveHint}>Role: {group.role}</span></div></section>
 </div></AppShell>;
}
