import '@testing-library/jest-dom/vitest';
import { render,screen,waitFor,within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,expect,it,vi } from 'vitest';
import { CardioController,type CardioLogInput,type CardioService,type CardioSnapshot } from '../../src/features/cardio';
import type { OnboardingProfile } from '../../src/features/onboarding';
const profile:OnboardingProfile={id:'user-cardio',username:'stefan',displayName:'Stefan',timezone:'America/Toronto',weeklyWorkoutTarget:4,pendingWeeklyWorkoutTarget:null,onboardingCompletedAt:'2026-08-21T00:00:00Z'};
function memoryService():CardioService{let snapshot:CardioSnapshot={summary:{totalActivities:0,totalActiveMinutes:0,last30DaysActivities:0,last30DaysActiveMinutes:0,last30DaysBonusXp:0,lastActivityAt:null},history:[]};return{async load(){return structuredClone(snapshot)},async log(input:CardioLogInput){snapshot={summary:{totalActivities:1,totalActiveMinutes:input.activeDurationMinutes,last30DaysActivities:1,last30DaysActiveMinutes:input.activeDurationMinutes,last30DaysBonusXp:10,lastActivityAt:'2026-08-21T12:00:00Z'},history:[{workoutId:'cardio-1',category:input.category,scoringDate:'2026-08-21',startedAt:'2026-08-21T12:00:00Z',endedAt:'2026-08-21T12:30:00Z',activeDurationSeconds:input.activeDurationMinutes*60,qualifiesCardioBonus:true,dailyBonusXp:10,notes:input.notes?.trim()||null}]};return'cardio-1'},async remove(){snapshot={summary:{totalActivities:0,totalActiveMinutes:0,last30DaysActivities:0,last30DaysActiveMinutes:0,last30DaysBonusXp:0,lastActivityAt:null},history:[]};return'cardio-1'}}}
describe('cardio accessory integration journey',()=>{it('logs and deletes secondary cardio without presenting it as a lifting day',async()=>{const user=userEvent.setup();render(<CardioController profile={profile} onNavigate={vi.fn()} onSignOut={vi.fn()} service={memoryService()}/>);expect(await screen.findByRole('heading',{name:'Log cardio'})).toBeInTheDocument();expect(screen.getByText(/never counts as a lifting day/i)).toBeInTheDocument();await user.selectOptions(screen.getByRole('combobox',{name:'Activity'}),'CYCLING');await user.clear(screen.getByRole('spinbutton',{name:'Active minutes'}));await user.type(screen.getByRole('spinbutton',{name:'Active minutes'}),'30');await user.click(screen.getByRole('button',{name:'Log cardio'}));const historySection=screen.getByRole('heading',{name:'Recent cardio'}).closest('section');expect(historySection).not.toBeNull();expect(within(historySection!).getByText('Cycling')).toBeInTheDocument();expect(screen.getByText('+10 XP daily bonus')).toBeInTheDocument();expect(screen.getByText(/do not increase weekly lifting-day consistency/i)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Delete Cycling/}));await waitFor(()=>expect(screen.getByText('No cardio logged yet.')).toBeInTheDocument())})});
