import { useMemo, useState } from 'react';
import { AppShell, type AppSection } from '../../../components/layout';
import { Button, SelectField } from '../../../components/ui';
import { liftingBadgeDefinition } from '../../consistency';
import type { GroupSummary } from '../../groups';
import type { OnboardingProfile } from '../../onboarding';
import { ProfilePicture } from '../../profile-picture';
import type { BadgeActivityMetadata, GoalActivityMetadata, GroupCompetitionLeaderboard, GroupCompetitionPeriod, GroupReactionType, GroupSocialFeedItem, LiftActivityMetadata, PrActivityMetadata } from '../model';
import styles from './GroupSocialScreen.module.css';
interface Props{profile:OnboardingProfile;groups:GroupSummary[];group:GroupSummary;weekly:GroupCompetitionLeaderboard;allTime:GroupCompetitionLeaderboard;feed:GroupSocialFeedItem[];hasMore:boolean;loadingMore:boolean;busyReactionKey:string|null;error:string;onNavigate:(section:AppSection)=>void;onSignOut:()=>void;onSelectGroup:(groupId:string)=>void;onLoadMore:()=>void;onReact:(activityKey:string,reaction:GroupReactionType)=>void;}
const reactionCopy:Record<GroupReactionType,string>={FIRE:'Fire',STRONG:'Strong',CLAP:'Clap'};
function shortDate(value:string):string{const date=new Date(value.length===10?`${value}T12:00:00.000Z`:value);return new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric'}).format(date);}
function relativeTime(value:string):string{const seconds=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return'just now';const minutes=Math.floor(seconds/60);if(minutes<60)return`${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours}h ago`;const days=Math.floor(hours/24);if(days<7)return`${days}d ago`;return shortDate(value);}
function prCopy(metadata:PrActivityMetadata):string{if(metadata.metricType==='BODYWEIGHT_REPS')return`${Math.round(metadata.metricValue)} reps`;const e1rm=`e1RM ${Math.round(metadata.metricValue)} kg`;if(metadata.weightKg===null)return e1rm;const weight=Math.round(metadata.weightKg*10)/10;return`${weight} kg${metadata.reps?` × ${metadata.reps}`:''} · ${e1rm}`;}
function activityContent(item:GroupSocialFeedItem):{kicker:string;title:string;detail:string}{if(item.activityType==='LIFT'){const m=item.metadata as LiftActivityMetadata;return{kicker:'Lift complete',title:m.title,detail:`${m.durationMinutes} min · ${m.exerciseCount} exercises · ${m.xp} XP`};}if(item.activityType==='PR'){const m=item.metadata as PrActivityMetadata;return{kicker:'New PR',title:m.exerciseName,detail:prCopy(m)};}if(item.activityType==='BADGE'){const m=item.metadata as BadgeActivityMetadata;const badge=liftingBadgeDefinition(m.badgeKey);return{kicker:'Badge earned',title:badge.title,detail:badge.description};}const m=item.metadata as GoalActivityMetadata;return{kicker:'Weekly goal hit',title:`${m.liftingDays}/${m.target} lifting days`,detail:`Week of ${shortDate(m.weekStart)}`};}
function leaderboardLabel(board:GroupCompetitionLeaderboard):string{if(board.period==='ALL_TIME')return'All authoritative lifting-v1 XP';if(!board.periodStart||!board.periodEnd)return'Current lifting week';return`${shortDate(board.periodStart)}–${shortDate(board.periodEnd)}`;}
export function GroupSocialScreen(props:Props){const{profile,groups,group,weekly,allTime,feed,hasMore,loadingMore,busyReactionKey,error,onNavigate,onSignOut,onSelectGroup,onLoadMore,onReact}=props;const[period,setPeriod]=useState<GroupCompetitionPeriod>('WEEK');const board=period==='WEEK'?weekly:allTime;const currentUser=useMemo(()=>board.entries.find(entry=>entry.isCurrentUser)??null,[board]);return <AppShell activeItem="compete" onNavigate={onNavigate} onSignOut={onSignOut} userLabel={profile.displayName} userMeta={`@${profile.username} · ${profile.weeklyWorkoutTarget} lift days`}><div className={styles.page}>
<header className={styles.header}><div><p className={styles.kicker}>COMPETE</p><h1>{group.name}</h1><p>Scoreboards and crew highlights from authoritative lifting activity.</p></div><div className={styles.headerActions}>{groups.length>1&&<SelectField label="Group" value={group.id} onChange={e=>onSelectGroup(e.target.value)}>{groups.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</SelectField>}<Button onClick={()=>onNavigate('groups')} variant="secondary">Manage group</Button></div></header>
<section className={styles.privacyNote} aria-label="Social privacy"><strong>Summary-only social feed</strong><span>Individual sets, workout notes, and full exercise details stay private. Reactions never affect XP.</span></section>
{error&&<p className={styles.error} role="alert">{error}</p>}
<section className={styles.competition} aria-labelledby="competition-heading"><div className={styles.sectionHeading}><div><p className={styles.sectionLabel}>Leaderboard</p><h2 id="competition-heading">Crew standings</h2><p>{leaderboardLabel(board)}</p></div><div className={styles.periodSwitch} role="group" aria-label="Leaderboard period"><button aria-pressed={period==='WEEK'} onClick={()=>setPeriod('WEEK')} type="button">This week</button><button aria-pressed={period==='ALL_TIME'} onClick={()=>setPeriod('ALL_TIME')} type="button">All time</button></div></div>
{currentUser&&<div className={styles.yourStanding}><span>Your standing</span><strong>#{currentUser.rank}</strong><b>{currentUser.xp} XP</b><small>{currentUser.liftingDays} lift days · {currentUser.prCount} PRs</small></div>}
<ol className={styles.leaderboard}>{board.entries.map(entry=><li className={`${styles.leaderboardRow}${entry.isCurrentUser?` ${styles.currentUser}`:''}`} key={entry.userId}><span className={styles.rank}>{entry.rank}</span><ProfilePicture displayName={entry.displayName} size="sm" src={entry.profilePictureUrl}/><div className={styles.identity}><strong>{entry.displayName}{entry.isCurrentUser?' (You)':''}</strong><span>@{entry.username}</span></div><div className={styles.supportingStats}><span>{entry.liftingDays} lift days</span><span>{entry.prCount} PRs</span><span>{entry.badgeCount} badges</span></div><b className={styles.xp}>{entry.xp} XP</b></li>)}</ol></section>
<section className={styles.feedSection} aria-labelledby="crew-feed-heading"><div className={styles.sectionHeading}><div><p className={styles.sectionLabel}>Crew activity</p><h2 id="crew-feed-heading">Highlights, not surveillance</h2><p>Qualifying lifts, real PRs, badges, and completed weekly goals only.</p></div></div>
{feed.length===0?<p className={styles.empty}>Crew highlights will appear after members complete qualifying lifting activity.</p>:<ul className={styles.feed}>{feed.map(item=>{const content=activityContent(item);return<li className={styles.feedCard} key={item.activityKey}><div className={styles.feedIdentity}><ProfilePicture displayName={item.displayName} size="sm" src={item.profilePictureUrl}/><div><strong>{item.displayName}</strong><span>@{item.username} · <time dateTime={item.activityAt}>{relativeTime(item.activityAt)}</time></span></div></div><div className={styles.feedBody}><span className={styles.activityType}>{content.kicker}</span><h3>{content.title}</h3><p>{content.detail}</p></div><div className={styles.reactions} aria-label={`Reactions to ${content.title}`}>{(Object.keys(reactionCopy) as GroupReactionType[]).map(reaction=><button aria-label={`${reactionCopy[reaction]} ${item.reactions[reaction]}`} aria-pressed={item.myReaction===reaction} disabled={busyReactionKey===item.activityKey} key={reaction} onClick={()=>onReact(item.activityKey,reaction)} type="button"><span>{reactionCopy[reaction]}</span><b>{item.reactions[reaction]}</b></button>)}</div></li>;})}</ul>}
{hasMore&&<div className={styles.loadMore}><Button disabled={loadingMore} onClick={onLoadMore} variant="secondary">{loadingMore?'Loading…':'Load more'}</Button></div>}</section>
</div></AppShell>;}
