import { useCallback, useEffect, useRef, useState } from 'react';
import type { GroupCompetitionLeaderboard, GroupReactionType, GroupSocialFeedItem, GroupSocialFeedPage } from '../model';
import { toUserFacingSocialError } from '../socialMessages';
import { createGroupSocialService, type GroupSocialService } from '../socialService';
export type GroupSocialStatus='loading'|'ready'|'error';
function withOptimisticReaction(item:GroupSocialFeedItem,next:GroupReactionType|null):GroupSocialFeedItem{const reactions={...item.reactions};if(item.myReaction)reactions[item.myReaction]=Math.max(0,reactions[item.myReaction]-1);if(next)reactions[next]+=1;return {...item,reactions,myReaction:next};}
export function useGroupSocial(groupId:string,injectedService?:GroupSocialService){
 const serviceRef=useRef<GroupSocialService|null>(null);if(!serviceRef.current)serviceRef.current=injectedService??createGroupSocialService();
 const[status,setStatus]=useState<GroupSocialStatus>('loading'),[error,setError]=useState('');const[weekly,setWeekly]=useState<GroupCompetitionLeaderboard|null>(null);const[feed,setFeed]=useState<GroupSocialFeedPage>({items:[],nextCursor:null});const[loadingMore,setLoadingMore]=useState(false),[busyReactionKey,setBusyReactionKey]=useState<string|null>(null);
 const load=useCallback(async()=>{setStatus('loading');setError('');try{const[nextWeekly,nextFeed]=await Promise.all([serviceRef.current!.loadGroupLeaderboard(groupId),serviceRef.current!.loadFeed(groupId)]);setWeekly(nextWeekly);setFeed(nextFeed);setStatus('ready');return true;}catch(caught){setError(toUserFacingSocialError(caught));setStatus('error');return false;}},[groupId]);
 useEffect(()=>{void load();},[load]);
 const loadMore=useCallback(async()=>{if(!feed.nextCursor||loadingMore)return;setLoadingMore(true);setError('');try{const page=await serviceRef.current!.loadFeed(groupId,feed.nextCursor);setFeed(current=>({items:[...current.items,...page.items.filter(item=>!current.items.some(existing=>existing.activityKey===item.activityKey))],nextCursor:page.nextCursor}));}catch(caught){setError(toUserFacingSocialError(caught));}finally{setLoadingMore(false);}},[feed.nextCursor,groupId,loadingMore]);
 const react=useCallback(async(activityKey:string,reaction:GroupReactionType)=>{if(busyReactionKey)return false;const current=feed.items.find(item=>item.activityKey===activityKey);if(!current)return false;const nextReaction=current.myReaction===reaction?null:reaction;const previous=current;setBusyReactionKey(activityKey);setError('');setFeed(state=>({...state,items:state.items.map(item=>item.activityKey===activityKey?withOptimisticReaction(item,nextReaction):item)}));try{await serviceRef.current!.setReaction(groupId,activityKey,nextReaction);return true;}catch(caught){setFeed(state=>({...state,items:state.items.map(item=>item.activityKey===activityKey?previous:item)}));setError(toUserFacingSocialError(caught));return false;}finally{setBusyReactionKey(null);}},[busyReactionKey,feed.items,groupId]);
 return {status,error,weekly,feed,loadingMore,busyReactionKey,retry:load,loadMore,react};
}
