-- Workout Game PWA — Phase 6.1C / 6.2 exercise picker metadata (v0.4.2)
-- Makes the canonical catalogue self-contained, browsable by muscle/workout type,
-- alias-aware, and capable of returning user-specific recents.

alter table public.exercise_catalog
  add column if not exists primary_muscle_group text not null default 'OTHER',
  add column if not exists workout_type text not null default 'OTHER',
  add column if not exists aliases text[] not null default array[]::text[];

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'exercise_catalog_primary_muscle_group_check'
      and conrelid = 'public.exercise_catalog'::regclass
  ) then
    alter table public.exercise_catalog
      add constraint exercise_catalog_primary_muscle_group_check
      check (primary_muscle_group in (
        'CHEST','BACK','SHOULDERS','BICEPS','TRICEPS','QUADS','HAMSTRINGS',
        'GLUTES','CALVES','CORE','FOREARMS_GRIP','NECK','FULL_BODY','OTHER'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'exercise_catalog_workout_type_check'
      and conrelid = 'public.exercise_catalog'::regclass
  ) then
    alter table public.exercise_catalog
      add constraint exercise_catalog_workout_type_check
      check (workout_type in (
        'BARBELL','DUMBBELL','KETTLEBELL','MACHINE','CABLE','BODYWEIGHT','ISOMETRIC',
        'PLYOMETRIC','MEDICINE_BALL','LANDMINE','BAND','STRONGMAN_CARRY_SLED',
        'OLYMPIC_POWER','SPECIALTY','OTHER'
      ));
  end if;
end;
$$;

insert into public.exercise_catalog (
  canonical_name,
  measurement_type,
  active,
  primary_muscle_group,
  workout_type,
  aliases
) values
  ('Barbell Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'BARBELL', array['Bench Press', 'Bench', 'BB Bench', 'BB Bench Press']::text[]),
  ('Incline Barbell Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'BARBELL', array['Incline Bench', 'Incline BB Bench', 'Incline BB Bench Press']::text[]),
  ('Decline Barbell Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'BARBELL', array['Decline BB Bench Press']::text[]),
  ('Close-Grip Barbell Bench Press', 'WEIGHT_REPS', true, 'TRICEPS', 'BARBELL', array['Close-Grip BB Bench Press', 'Close Grip Barbell Bench Press']::text[]),
  ('Barbell Floor Press', 'WEIGHT_REPS', true, 'CHEST', 'BARBELL', array['BB Floor Press']::text[]),
  ('Overhead Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'BARBELL', array['OHP', 'Military Press', 'Barbell OHP']::text[]),
  ('Push Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'BARBELL', array[]::text[]),
  ('Barbell Front Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'BARBELL', array['BB Front Raise']::text[]),
  ('Back Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['Squat', 'Barbell Squat', 'BB Squat']::text[]),
  ('Front Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['Barbell Front Squat']::text[]),
  ('Zercher Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array[]::text[]),
  ('Box Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array[]::text[]),
  ('Pause Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array[]::text[]),
  ('Barbell Hack Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['BB Hack Squat']::text[]),
  ('Jefferson Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array[]::text[]),
  ('Deadlift', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array['Conventional Deadlift']::text[]),
  ('Sumo Deadlift', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array['Sumo DL']::text[]),
  ('Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'BARBELL', array['RDL', 'Barbell RDL']::text[]),
  ('Stiff-Leg Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'BARBELL', array[]::text[]),
  ('Deficit Deadlift', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array[]::text[]),
  ('Rack Pull', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array[]::text[]),
  ('Snatch-Grip Deadlift', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array[]::text[]),
  ('Good Morning', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'BARBELL', array[]::text[]),
  ('Barbell Row', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array['Bent Over Row', 'Bent-Over Barbell Row', 'BB Row']::text[]),
  ('Pendlay Row', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array['Pendlay']::text[]),
  ('Barbell Shrug', 'WEIGHT_REPS', true, 'BACK', 'BARBELL', array['BB Shrug']::text[]),
  ('Barbell Hip Thrust', 'WEIGHT_REPS', true, 'GLUTES', 'BARBELL', array['Hip Thrust', 'BB Hip Thrust']::text[]),
  ('Barbell Glute Bridge', 'WEIGHT_REPS', true, 'GLUTES', 'BARBELL', array['BB Glute Bridge']::text[]),
  ('Barbell Reverse Lunge', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['BB Reverse Lunge']::text[]),
  ('Barbell Walking Lunge', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['BB Walking Lunge']::text[]),
  ('Barbell Bulgarian Split Squat', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['BB Bulgarian Split Squat', 'Barbell BSS', 'BB BSS']::text[]),
  ('Barbell Step-Up', 'WEIGHT_REPS', true, 'QUADS', 'BARBELL', array['BB Step-Up']::text[]),
  ('Barbell Calf Raise', 'WEIGHT_REPS', true, 'CALVES', 'BARBELL', array['BB Calf Raise']::text[]),
  ('Barbell Biceps Curl', 'WEIGHT_REPS', true, 'BICEPS', 'BARBELL', array['BB Biceps Curl']::text[]),
  ('Barbell Reverse Curl', 'WEIGHT_REPS', true, 'BICEPS', 'BARBELL', array['BB Reverse Curl']::text[]),
  ('Biceps Curl', 'WEIGHT_REPS', true, 'BICEPS', 'BARBELL', array[]::text[]),
  ('EZ-Bar Curl', 'WEIGHT_REPS', true, 'BICEPS', 'BARBELL', array[]::text[]),
  ('EZ-Bar Skull Crusher', 'WEIGHT_REPS', true, 'TRICEPS', 'BARBELL', array[]::text[]),
  ('Barbell Skull Crusher', 'WEIGHT_REPS', true, 'TRICEPS', 'BARBELL', array['BB Skull Crusher']::text[]),
  ('Triceps Extension', 'WEIGHT_REPS', true, 'TRICEPS', 'BARBELL', array[]::text[]),
  ('Power Clean', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Hang Power Clean', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Clean', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Clean and Jerk', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Power Snatch', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Hang Power Snatch', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Snatch', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Clean Pull', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Snatch Pull', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('High Pull', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Push Jerk', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Split Jerk', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array[]::text[]),
  ('Barbell Thruster', 'WEIGHT_REPS', true, 'FULL_BODY', 'OLYMPIC_POWER', array['BB Thruster']::text[]),
  ('Dumbbell Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['DB Bench', 'DB Bench Press']::text[]),
  ('Incline Dumbbell Press', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['Incline DB Press', 'Incline DB Bench']::text[]),
  ('Decline Dumbbell Press', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['Decline DB Press']::text[]),
  ('Dumbbell Floor Press', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['DB Floor Press']::text[]),
  ('Dumbbell Squeeze Press', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['DB Squeeze Press']::text[]),
  ('Dumbbell Fly', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['DB Fly']::text[]),
  ('Incline Dumbbell Fly', 'WEIGHT_REPS', true, 'CHEST', 'DUMBBELL', array['Incline DB Fly']::text[]),
  ('Dumbbell Pullover', 'WEIGHT_REPS', true, 'BACK', 'DUMBBELL', array['DB Pullover']::text[]),
  ('Dumbbell Shoulder Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'DUMBBELL', array['DB Shoulder Press', 'DB OHP']::text[]),
  ('Arnold Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'DUMBBELL', array[]::text[]),
  ('Dumbbell Push Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'DUMBBELL', array['DB Push Press']::text[]),
  ('Dumbbell Lateral Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'DUMBBELL', array['DB Lateral Raise']::text[]),
  ('Dumbbell Front Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'DUMBBELL', array['DB Front Raise']::text[]),
  ('Dumbbell Reverse Fly', 'WEIGHT_REPS', true, 'SHOULDERS', 'DUMBBELL', array['DB Reverse Fly']::text[]),
  ('Dumbbell Row', 'WEIGHT_REPS', true, 'BACK', 'DUMBBELL', array['DB Row', 'One Arm Dumbbell Row']::text[]),
  ('Chest-Supported Dumbbell Row', 'WEIGHT_REPS', true, 'BACK', 'DUMBBELL', array['Chest-Supported DB Row']::text[]),
  ('Dumbbell Renegade Row', 'WEIGHT_REPS', true, 'BACK', 'DUMBBELL', array['DB Renegade Row']::text[]),
  ('Dumbbell Shrug', 'WEIGHT_REPS', true, 'BACK', 'DUMBBELL', array['DB Shrug']::text[]),
  ('Dumbbell Biceps Curl', 'WEIGHT_REPS', true, 'BICEPS', 'DUMBBELL', array['DB Biceps Curl']::text[]),
  ('Dumbbell Hammer Curl', 'WEIGHT_REPS', true, 'BICEPS', 'DUMBBELL', array['DB Hammer Curl']::text[]),
  ('Incline Dumbbell Curl', 'WEIGHT_REPS', true, 'BICEPS', 'DUMBBELL', array['Incline DB Curl']::text[]),
  ('Concentration Curl', 'WEIGHT_REPS', true, 'BICEPS', 'DUMBBELL', array[]::text[]),
  ('Dumbbell Preacher Curl', 'WEIGHT_REPS', true, 'BICEPS', 'DUMBBELL', array['DB Preacher Curl']::text[]),
  ('Dumbbell Triceps Extension', 'WEIGHT_REPS', true, 'TRICEPS', 'DUMBBELL', array['DB Triceps Extension']::text[]),
  ('Dumbbell Skull Crusher', 'WEIGHT_REPS', true, 'TRICEPS', 'DUMBBELL', array['DB Skull Crusher']::text[]),
  ('Dumbbell Triceps Kickback', 'WEIGHT_REPS', true, 'TRICEPS', 'DUMBBELL', array['DB Triceps Kickback']::text[]),
  ('Goblet Squat', 'WEIGHT_REPS', true, 'QUADS', 'DUMBBELL', array[]::text[]),
  ('Dumbbell Front Squat', 'WEIGHT_REPS', true, 'QUADS', 'DUMBBELL', array['DB Front Squat']::text[]),
  ('Dumbbell Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'DUMBBELL', array['DB RDL', 'DB Romanian Deadlift', 'Dumbbell RDL']::text[]),
  ('Dumbbell Single-Leg Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'DUMBBELL', array['DB Single Leg RDL', 'DB SL RDL', 'DB Single-Leg Romanian Deadlift', 'Dumbbell Single-Leg RDL', 'Dumbbell Single Leg Romanian Deadlift', 'DB Single-Leg RDL']::text[]),
  ('Dumbbell Reverse Lunge', 'WEIGHT_REPS', true, 'QUADS', 'DUMBBELL', array['DB Reverse Lunge']::text[]),
  ('Dumbbell Walking Lunge', 'WEIGHT_REPS', true, 'QUADS', 'DUMBBELL', array['DB Walking Lunge']::text[]),
  ('Dumbbell Bulgarian Split Squat', 'WEIGHT_REPS', true, 'QUADS', 'DUMBBELL', array['DB Bulgarian Split Squat', 'DB BSS', 'Dumbbell BSS']::text[]),
  ('Dumbbell Step-Up', 'WEIGHT_REPS', true, 'QUADS', 'DUMBBELL', array['DB Step-Up']::text[]),
  ('Dumbbell Calf Raise', 'WEIGHT_REPS', true, 'CALVES', 'DUMBBELL', array['DB Calf Raise']::text[]),
  ('Kettlebell Swing', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB Swing']::text[]),
  ('Single-Arm Kettlebell Swing', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['Single Arm KB Swing', 'Single-Arm KB Swing']::text[]),
  ('Kettlebell Goblet Squat', 'WEIGHT_REPS', true, 'QUADS', 'KETTLEBELL', array['KB Goblet Squat']::text[]),
  ('Kettlebell Front Rack Squat', 'WEIGHT_REPS', true, 'QUADS', 'KETTLEBELL', array['KB Front Rack Squat']::text[]),
  ('Double Kettlebell Front Squat', 'WEIGHT_REPS', true, 'QUADS', 'KETTLEBELL', array['Double KB Front Squat']::text[]),
  ('Kettlebell Deadlift', 'WEIGHT_REPS', true, 'BACK', 'KETTLEBELL', array['KB Deadlift']::text[]),
  ('Kettlebell Sumo Deadlift', 'WEIGHT_REPS', true, 'BACK', 'KETTLEBELL', array['KB Sumo Deadlift']::text[]),
  ('Kettlebell Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'KETTLEBELL', array['KB RDL', 'KB Romanian Deadlift', 'Kettlebell RDL']::text[]),
  ('Kettlebell Single-Leg Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'KETTLEBELL', array['KB Single Leg RDL', 'KB SL RDL', 'KB Single-Leg Romanian Deadlift', 'Kettlebell Single-Leg RDL', 'Kettlebell Single Leg Romanian Deadlift', 'KB Single-Leg RDL']::text[]),
  ('Kettlebell Clean', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB Clean']::text[]),
  ('Double Kettlebell Clean', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['Double KB Clean']::text[]),
  ('Kettlebell Snatch', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB Snatch']::text[]),
  ('Kettlebell Strict Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'KETTLEBELL', array['KB Press', 'KB Strict Press']::text[]),
  ('Kettlebell Push Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'KETTLEBELL', array['KB Push Press']::text[]),
  ('Kettlebell Jerk', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB Jerk']::text[]),
  ('Kettlebell Clean and Press', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB Clean and Press']::text[]),
  ('Kettlebell Thruster', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB Thruster']::text[]),
  ('Turkish Get-Up', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['TGU']::text[]),
  ('Kettlebell Windmill', 'WEIGHT_REPS', true, 'CORE', 'KETTLEBELL', array['KB Windmill']::text[]),
  ('Kettlebell Halo', 'WEIGHT_REPS', true, 'SHOULDERS', 'KETTLEBELL', array['KB Halo']::text[]),
  ('Kettlebell High Pull', 'WEIGHT_REPS', true, 'FULL_BODY', 'KETTLEBELL', array['KB High Pull']::text[]),
  ('Kettlebell Gorilla Row', 'WEIGHT_REPS', true, 'BACK', 'KETTLEBELL', array['KB Gorilla Row']::text[]),
  ('Kettlebell Bent-Over Row', 'WEIGHT_REPS', true, 'BACK', 'KETTLEBELL', array['KB Bent-Over Row']::text[]),
  ('Kettlebell Renegade Row', 'WEIGHT_REPS', true, 'BACK', 'KETTLEBELL', array['KB Renegade Row']::text[]),
  ('Kettlebell Floor Press', 'WEIGHT_REPS', true, 'CHEST', 'KETTLEBELL', array['KB Floor Press']::text[]),
  ('Kettlebell Bottoms-Up Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'KETTLEBELL', array['KB Bottoms-Up Press']::text[]),
  ('Kettlebell Suitcase Deadlift', 'WEIGHT_REPS', true, 'BACK', 'KETTLEBELL', array['KB Suitcase Deadlift']::text[]),
  ('Kettlebell Lunge', 'WEIGHT_REPS', true, 'QUADS', 'KETTLEBELL', array['KB Lunge']::text[]),
  ('Kettlebell Cossack Squat', 'WEIGHT_REPS', true, 'QUADS', 'KETTLEBELL', array['KB Cossack Squat']::text[]),
  ('Kettlebell Farmer Carry', 'OTHER', true, 'FOREARMS_GRIP', 'KETTLEBELL', array['KB Farmer Carry']::text[]),
  ('Kettlebell Suitcase Carry', 'OTHER', true, 'FOREARMS_GRIP', 'KETTLEBELL', array['KB Suitcase Carry']::text[]),
  ('Kettlebell Front Rack Carry', 'OTHER', true, 'FOREARMS_GRIP', 'KETTLEBELL', array['KB Front Rack Carry']::text[]),
  ('Kettlebell Overhead Carry', 'OTHER', true, 'FOREARMS_GRIP', 'KETTLEBELL', array['KB Overhead Carry']::text[]),
  ('Machine Chest Press', 'WEIGHT_REPS', true, 'CHEST', 'MACHINE', array[]::text[]),
  ('Incline Machine Chest Press', 'WEIGHT_REPS', true, 'CHEST', 'MACHINE', array[]::text[]),
  ('Pec Deck Fly', 'WEIGHT_REPS', true, 'CHEST', 'MACHINE', array[]::text[]),
  ('Reverse Pec Deck Fly', 'WEIGHT_REPS', true, 'SHOULDERS', 'MACHINE', array[]::text[]),
  ('Machine Shoulder Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'MACHINE', array[]::text[]),
  ('Machine Lateral Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'MACHINE', array[]::text[]),
  ('Lat Pulldown', 'WEIGHT_REPS', true, 'BACK', 'MACHINE', array['Lat Pull Down']::text[]),
  ('Close-Grip Lat Pulldown', 'WEIGHT_REPS', true, 'BACK', 'MACHINE', array['Close Grip Lat Pulldown']::text[]),
  ('Machine Seated Row', 'WEIGHT_REPS', true, 'BACK', 'MACHINE', array[]::text[]),
  ('Machine High Row', 'WEIGHT_REPS', true, 'BACK', 'MACHINE', array[]::text[]),
  ('Machine Low Row', 'WEIGHT_REPS', true, 'BACK', 'MACHINE', array[]::text[]),
  ('Assisted Pull-Up', 'OTHER', true, 'BACK', 'MACHINE', array['Assisted Pullup']::text[]),
  ('Assisted Dip', 'OTHER', true, 'TRICEPS', 'MACHINE', array[]::text[]),
  ('Leg Press', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array['45 Degree Leg Press']::text[]),
  ('Single-Leg Press', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array['Single Leg Press']::text[]),
  ('Hack Squat Machine', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array[]::text[]),
  ('Pendulum Squat', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array[]::text[]),
  ('Belt Squat', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array[]::text[]),
  ('Leg Extension', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array[]::text[]),
  ('Single-Leg Extension', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array['Single Leg Extension']::text[]),
  ('Seated Leg Curl', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'MACHINE', array[]::text[]),
  ('Lying Leg Curl', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'MACHINE', array[]::text[]),
  ('Standing Leg Curl', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'MACHINE', array[]::text[]),
  ('Hip Abduction Machine', 'WEIGHT_REPS', true, 'GLUTES', 'MACHINE', array[]::text[]),
  ('Hip Adduction Machine', 'WEIGHT_REPS', true, 'GLUTES', 'MACHINE', array[]::text[]),
  ('Glute Drive Machine', 'WEIGHT_REPS', true, 'GLUTES', 'MACHINE', array[]::text[]),
  ('Standing Calf Raise Machine', 'WEIGHT_REPS', true, 'CALVES', 'MACHINE', array[]::text[]),
  ('Seated Calf Raise Machine', 'WEIGHT_REPS', true, 'CALVES', 'MACHINE', array[]::text[]),
  ('Machine Preacher Curl', 'WEIGHT_REPS', true, 'BICEPS', 'MACHINE', array[]::text[]),
  ('Machine Biceps Curl', 'WEIGHT_REPS', true, 'BICEPS', 'MACHINE', array[]::text[]),
  ('Machine Triceps Extension', 'WEIGHT_REPS', true, 'TRICEPS', 'MACHINE', array[]::text[]),
  ('Smith Machine Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'MACHINE', array['Smith Bench Press']::text[]),
  ('Smith Machine Incline Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'MACHINE', array['Smith Incline Bench Press']::text[]),
  ('Smith Machine Squat', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array['Smith Squat']::text[]),
  ('Smith Machine Front Squat', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array['Smith Front Squat']::text[]),
  ('Smith Machine Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'MACHINE', array['Smith Romanian Deadlift', 'Smith Machine RDL']::text[]),
  ('Smith Machine Bulgarian Split Squat', 'WEIGHT_REPS', true, 'QUADS', 'MACHINE', array['Smith Bulgarian Split Squat', 'Smith Machine BSS']::text[]),
  ('Smith Machine Hip Thrust', 'WEIGHT_REPS', true, 'GLUTES', 'MACHINE', array['Smith Hip Thrust']::text[]),
  ('Smith Machine Calf Raise', 'WEIGHT_REPS', true, 'CALVES', 'MACHINE', array['Smith Calf Raise']::text[]),
  ('Cable Chest Fly', 'WEIGHT_REPS', true, 'CHEST', 'CABLE', array[]::text[]),
  ('Low-to-High Cable Fly', 'WEIGHT_REPS', true, 'CHEST', 'CABLE', array[]::text[]),
  ('High-to-Low Cable Fly', 'WEIGHT_REPS', true, 'CHEST', 'CABLE', array[]::text[]),
  ('Cable Crossover', 'WEIGHT_REPS', true, 'CHEST', 'CABLE', array[]::text[]),
  ('Cable Chest Press', 'WEIGHT_REPS', true, 'CHEST', 'CABLE', array[]::text[]),
  ('Seated Cable Row', 'WEIGHT_REPS', true, 'BACK', 'CABLE', array[]::text[]),
  ('Single-Arm Cable Row', 'WEIGHT_REPS', true, 'BACK', 'CABLE', array[]::text[]),
  ('Cable Face Pull', 'WEIGHT_REPS', true, 'SHOULDERS', 'CABLE', array[]::text[]),
  ('Straight-Arm Pulldown', 'WEIGHT_REPS', true, 'BACK', 'CABLE', array[]::text[]),
  ('Cable Pullover', 'WEIGHT_REPS', true, 'BACK', 'CABLE', array[]::text[]),
  ('Cable Lateral Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'CABLE', array[]::text[]),
  ('Cable Front Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'CABLE', array[]::text[]),
  ('Cable Reverse Fly', 'WEIGHT_REPS', true, 'SHOULDERS', 'CABLE', array[]::text[]),
  ('Cable Y-Raise', 'WEIGHT_REPS', true, 'SHOULDERS', 'CABLE', array[]::text[]),
  ('Cable Biceps Curl', 'WEIGHT_REPS', true, 'BICEPS', 'CABLE', array['Cable Curl']::text[]),
  ('Bayesian Cable Curl', 'WEIGHT_REPS', true, 'BICEPS', 'CABLE', array[]::text[]),
  ('Rope Hammer Curl', 'WEIGHT_REPS', true, 'BICEPS', 'CABLE', array[]::text[]),
  ('Cable Triceps Pushdown', 'WEIGHT_REPS', true, 'TRICEPS', 'CABLE', array['Triceps Pushdown']::text[]),
  ('Rope Triceps Pushdown', 'WEIGHT_REPS', true, 'TRICEPS', 'CABLE', array['Rope Pushdown']::text[]),
  ('Overhead Cable Triceps Extension', 'WEIGHT_REPS', true, 'TRICEPS', 'CABLE', array[]::text[]),
  ('Single-Arm Cable Triceps Extension', 'WEIGHT_REPS', true, 'TRICEPS', 'CABLE', array[]::text[]),
  ('Cable Triceps Kickback', 'WEIGHT_REPS', true, 'TRICEPS', 'CABLE', array[]::text[]),
  ('Cable Crunch', 'WEIGHT_REPS', true, 'CORE', 'CABLE', array[]::text[]),
  ('Pallof Press', 'WEIGHT_REPS', true, 'CORE', 'CABLE', array['Pallof']::text[]),
  ('Cable Wood Chop', 'WEIGHT_REPS', true, 'CORE', 'CABLE', array[]::text[]),
  ('Cable Reverse Wood Chop', 'WEIGHT_REPS', true, 'CORE', 'CABLE', array[]::text[]),
  ('Cable Pull-Through', 'WEIGHT_REPS', true, 'GLUTES', 'CABLE', array[]::text[]),
  ('Cable Hip Abduction', 'WEIGHT_REPS', true, 'GLUTES', 'CABLE', array[]::text[]),
  ('Cable Hip Adduction', 'WEIGHT_REPS', true, 'GLUTES', 'CABLE', array[]::text[]),
  ('Cable Glute Kickback', 'WEIGHT_REPS', true, 'TRICEPS', 'CABLE', array[]::text[]),
  ('Cable External Rotation', 'WEIGHT_REPS', true, 'CORE', 'CABLE', array[]::text[]),
  ('Cable Internal Rotation', 'WEIGHT_REPS', true, 'CORE', 'CABLE', array[]::text[]),
  ('Pull-Up', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array['Pullup']::text[]),
  ('Chin-Up', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array['Chinup']::text[]),
  ('Neutral-Grip Pull-Up', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array[]::text[]),
  ('Wide-Grip Pull-Up', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array[]::text[]),
  ('Commando Pull-Up', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array[]::text[]),
  ('Scapular Pull-Up', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array[]::text[]),
  ('Muscle-Up', 'BODYWEIGHT_REPS', true, 'FULL_BODY', 'BODYWEIGHT', array['Muscle Up']::text[]),
  ('Inverted Row', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array[]::text[]),
  ('Ring Row', 'BODYWEIGHT_REPS', true, 'BACK', 'BODYWEIGHT', array[]::text[]),
  ('Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array['Pushup']::text[]),
  ('Incline Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array[]::text[]),
  ('Decline Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array[]::text[]),
  ('Diamond Push-Up', 'BODYWEIGHT_REPS', true, 'TRICEPS', 'BODYWEIGHT', array[]::text[]),
  ('Wide-Grip Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array[]::text[]),
  ('Pike Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array[]::text[]),
  ('Handstand Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array['HSPU']::text[]),
  ('Ring Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array[]::text[]),
  ('Scapular Push-Up', 'BODYWEIGHT_REPS', true, 'CHEST', 'BODYWEIGHT', array[]::text[]),
  ('Dip', 'BODYWEIGHT_REPS', true, 'TRICEPS', 'BODYWEIGHT', array[]::text[]),
  ('Ring Dip', 'BODYWEIGHT_REPS', true, 'TRICEPS', 'BODYWEIGHT', array[]::text[]),
  ('Bodyweight Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array['BW Squat']::text[]),
  ('Bodyweight Split Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array['BW Split Squat']::text[]),
  ('Bodyweight Bulgarian Split Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array['BW Bulgarian Split Squat', 'BW BSS', 'Bodyweight BSS']::text[]),
  ('Bodyweight Reverse Lunge', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array['BW Reverse Lunge']::text[]),
  ('Bodyweight Walking Lunge', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array['BW Walking Lunge']::text[]),
  ('Bodyweight Step-Up', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array['BW Step-Up']::text[]),
  ('Pistol Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array[]::text[]),
  ('Shrimp Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array[]::text[]),
  ('Sissy Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array[]::text[]),
  ('Cossack Squat', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array[]::text[]),
  ('Nordic Hamstring Curl', 'BODYWEIGHT_REPS', true, 'HAMSTRINGS', 'BODYWEIGHT', array['Nordic Curl']::text[]),
  ('Reverse Nordic Curl', 'BODYWEIGHT_REPS', true, 'QUADS', 'BODYWEIGHT', array[]::text[]),
  ('Glute Bridge', 'BODYWEIGHT_REPS', true, 'GLUTES', 'BODYWEIGHT', array[]::text[]),
  ('Single-Leg Glute Bridge', 'BODYWEIGHT_REPS', true, 'GLUTES', 'BODYWEIGHT', array['Single Leg Glute Bridge']::text[]),
  ('Bodyweight Hip Thrust', 'BODYWEIGHT_REPS', true, 'GLUTES', 'BODYWEIGHT', array['BW Hip Thrust']::text[]),
  ('Calf Raise', 'BODYWEIGHT_REPS', true, 'CALVES', 'BODYWEIGHT', array[]::text[]),
  ('Single-Leg Calf Raise', 'BODYWEIGHT_REPS', true, 'CALVES', 'BODYWEIGHT', array['Single Leg Calf Raise']::text[]),
  ('Hanging Leg Raise', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Hanging Knee Raise', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Toes-to-Bar', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Sit-Up', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Crunch', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Bicycle Crunch', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Dead Bug', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Bird Dog', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Ab Wheel Rollout', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Mountain Climber', 'BODYWEIGHT_REPS', true, 'CORE', 'BODYWEIGHT', array[]::text[]),
  ('Front Plank', 'DURATION', true, 'CORE', 'ISOMETRIC', array[]::text[]),
  ('Side Plank', 'DURATION', true, 'CORE', 'ISOMETRIC', array[]::text[]),
  ('Copenhagen Plank', 'DURATION', true, 'CORE', 'ISOMETRIC', array[]::text[]),
  ('Hollow Body Hold', 'DURATION', true, 'CORE', 'ISOMETRIC', array[]::text[]),
  ('Superman Hold', 'DURATION', true, 'BACK', 'ISOMETRIC', array[]::text[]),
  ('Wall Sit', 'DURATION', true, 'QUADS', 'ISOMETRIC', array[]::text[]),
  ('L-Sit', 'DURATION', true, 'CORE', 'ISOMETRIC', array[]::text[]),
  ('Dead Hang', 'DURATION', true, 'FOREARMS_GRIP', 'ISOMETRIC', array[]::text[]),
  ('Flexed-Arm Hang', 'DURATION', true, 'BACK', 'ISOMETRIC', array[]::text[]),
  ('Box Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array['Box Jumps']::text[]),
  ('Depth Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Drop Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Broad Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array['Broad Jumps']::text[]),
  ('Vertical Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Tuck Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Squat Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Split Squat Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Jumping Lunge', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Skater Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Lateral Bound', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Single-Leg Broad Jump', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array['Single Leg Broad Jump']::text[]),
  ('Pogo Jump', 'OTHER', true, 'CALVES', 'PLYOMETRIC', array[]::text[]),
  ('Hurdle Hop', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Lateral Hurdle Hop', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Bounds', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Power Skip', 'OTHER', true, 'QUADS', 'PLYOMETRIC', array[]::text[]),
  ('Burpee', 'OTHER', true, 'FULL_BODY', 'PLYOMETRIC', array[]::text[]),
  ('Burpee Box Jump', 'OTHER', true, 'FULL_BODY', 'PLYOMETRIC', array[]::text[]),
  ('Clap Push-Up', 'OTHER', true, 'CHEST', 'PLYOMETRIC', array[]::text[]),
  ('Plyometric Push-Up', 'OTHER', true, 'CHEST', 'PLYOMETRIC', array[]::text[]),
  ('Jump Rope', 'DURATION', true, 'CALVES', 'PLYOMETRIC', array[]::text[]),
  ('Double-Under', 'OTHER', true, 'CALVES', 'PLYOMETRIC', array['Double Under', 'DU']::text[]),
  ('Medicine Ball Chest Pass', 'OTHER', true, 'CHEST', 'MEDICINE_BALL', array['Med Ball Chest Pass']::text[]),
  ('Medicine Ball Overhead Throw', 'OTHER', true, 'FULL_BODY', 'MEDICINE_BALL', array['Med Ball Overhead Throw']::text[]),
  ('Medicine Ball Slam', 'OTHER', true, 'FULL_BODY', 'MEDICINE_BALL', array['Med Ball Slam']::text[]),
  ('Medicine Ball Rotational Throw', 'OTHER', true, 'FULL_BODY', 'MEDICINE_BALL', array['Med Ball Rotational Throw']::text[]),
  ('Medicine Ball Scoop Toss', 'OTHER', true, 'FULL_BODY', 'MEDICINE_BALL', array['Med Ball Scoop Toss']::text[]),
  ('Medicine Ball Shot-Put Throw', 'OTHER', true, 'FULL_BODY', 'MEDICINE_BALL', array['Med Ball Shot-Put Throw']::text[]),
  ('Medicine Ball Sit-Up Throw', 'OTHER', true, 'CORE', 'MEDICINE_BALL', array['Med Ball Sit-Up Throw']::text[]),
  ('Medicine Ball Russian Twist', 'OTHER', true, 'CORE', 'MEDICINE_BALL', array['Med Ball Russian Twist']::text[]),
  ('Landmine Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'LANDMINE', array[]::text[]),
  ('Single-Arm Landmine Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'LANDMINE', array[]::text[]),
  ('Half-Kneeling Landmine Press', 'WEIGHT_REPS', true, 'SHOULDERS', 'LANDMINE', array[]::text[]),
  ('Landmine Squat', 'WEIGHT_REPS', true, 'QUADS', 'LANDMINE', array[]::text[]),
  ('Landmine Hack Squat', 'WEIGHT_REPS', true, 'QUADS', 'LANDMINE', array[]::text[]),
  ('Landmine Romanian Deadlift', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'LANDMINE', array['Landmine RDL']::text[]),
  ('Landmine Row', 'WEIGHT_REPS', true, 'BACK', 'LANDMINE', array[]::text[]),
  ('Meadows Row', 'WEIGHT_REPS', true, 'BACK', 'LANDMINE', array['Meadows']::text[]),
  ('Landmine Reverse Lunge', 'WEIGHT_REPS', true, 'QUADS', 'LANDMINE', array[]::text[]),
  ('Landmine Thruster', 'WEIGHT_REPS', true, 'FULL_BODY', 'LANDMINE', array[]::text[]),
  ('Landmine Rotation', 'WEIGHT_REPS', true, 'CORE', 'LANDMINE', array[]::text[]),
  ('Band Pull-Apart', 'OTHER', true, 'SHOULDERS', 'BAND', array['Band Pull Apart']::text[]),
  ('Band Face Pull', 'OTHER', true, 'SHOULDERS', 'BAND', array[]::text[]),
  ('Band Row', 'OTHER', true, 'BACK', 'BAND', array[]::text[]),
  ('Band Chest Press', 'OTHER', true, 'CHEST', 'BAND', array[]::text[]),
  ('Band-Resisted Push-Up', 'OTHER', true, 'CHEST', 'BAND', array[]::text[]),
  ('Band Overhead Press', 'OTHER', true, 'SHOULDERS', 'BAND', array[]::text[]),
  ('Band Lateral Raise', 'OTHER', true, 'SHOULDERS', 'BAND', array[]::text[]),
  ('Band Biceps Curl', 'OTHER', true, 'BICEPS', 'BAND', array[]::text[]),
  ('Band Triceps Extension', 'OTHER', true, 'TRICEPS', 'BAND', array[]::text[]),
  ('Band Squat', 'OTHER', true, 'QUADS', 'BAND', array[]::text[]),
  ('Band Good Morning', 'OTHER', true, 'HAMSTRINGS', 'BAND', array[]::text[]),
  ('Band Lateral Walk', 'OTHER', true, 'GLUTES', 'BAND', array[]::text[]),
  ('Band Monster Walk', 'OTHER', true, 'GLUTES', 'BAND', array[]::text[]),
  ('Band External Rotation', 'OTHER', true, 'CORE', 'BAND', array[]::text[]),
  ('Band Internal Rotation', 'OTHER', true, 'CORE', 'BAND', array[]::text[]),
  ('Farmer Carry', 'OTHER', true, 'FOREARMS_GRIP', 'STRONGMAN_CARRY_SLED', array['Farmers Carry', 'Farmer Walk']::text[]),
  ('Suitcase Carry', 'OTHER', true, 'FOREARMS_GRIP', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Front Rack Carry', 'OTHER', true, 'FOREARMS_GRIP', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Overhead Carry', 'OTHER', true, 'FOREARMS_GRIP', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Yoke Walk', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Zercher Carry', 'OTHER', true, 'FOREARMS_GRIP', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Bear Hug Carry', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Sandbag Carry', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Sled Push', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Sled Pull', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Prowler Push', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Backward Sled Drag', 'OTHER', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Tire Flip', 'WEIGHT_REPS', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Sandbag Clean', 'WEIGHT_REPS', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Sandbag Squat', 'WEIGHT_REPS', true, 'QUADS', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Sandbag Shouldering', 'WEIGHT_REPS', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Atlas Stone Load', 'WEIGHT_REPS', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Log Press', 'WEIGHT_REPS', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Axle Deadlift', 'WEIGHT_REPS', true, 'BACK', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Viking Press', 'WEIGHT_REPS', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Rope Climb', 'BODYWEIGHT_REPS', true, 'BACK', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Battle Ropes', 'DURATION', true, 'FULL_BODY', 'STRONGMAN_CARRY_SLED', array[]::text[]),
  ('Trap Bar Deadlift', 'WEIGHT_REPS', true, 'BACK', 'SPECIALTY', array['Hex Bar Deadlift']::text[]),
  ('Trap Bar Shrug', 'WEIGHT_REPS', true, 'BACK', 'SPECIALTY', array[]::text[]),
  ('Trap Bar Farmer Carry', 'OTHER', true, 'FOREARMS_GRIP', 'SPECIALTY', array[]::text[]),
  ('Safety Bar Squat', 'WEIGHT_REPS', true, 'QUADS', 'SPECIALTY', array['SSB Squat']::text[]),
  ('Cambered Bar Squat', 'WEIGHT_REPS', true, 'QUADS', 'SPECIALTY', array[]::text[]),
  ('Swiss Bar Bench Press', 'WEIGHT_REPS', true, 'CHEST', 'SPECIALTY', array['Football Bar Bench Press']::text[]),
  ('Floor Skull Crusher', 'WEIGHT_REPS', true, 'TRICEPS', 'SPECIALTY', array[]::text[]),
  ('Jefferson Curl', 'WEIGHT_REPS', true, 'HAMSTRINGS', 'SPECIALTY', array[]::text[]),
  ('Reverse Hyperextension', 'WEIGHT_REPS', true, 'BACK', 'SPECIALTY', array[]::text[]),
  ('45-Degree Back Extension', 'WEIGHT_REPS', true, 'BACK', 'SPECIALTY', array['45 Degree Back Extension']::text[]),
  ('Back Extension', 'BODYWEIGHT_REPS', true, 'BACK', 'SPECIALTY', array[]::text[]),
  ('GHD Hip Extension', 'BODYWEIGHT_REPS', true, 'BACK', 'SPECIALTY', array[]::text[]),
  ('GHD Sit-Up', 'BODYWEIGHT_REPS', true, 'CORE', 'SPECIALTY', array[]::text[]),
  ('Tibialis Raise', 'BODYWEIGHT_REPS', true, 'CALVES', 'SPECIALTY', array[]::text[]),
  ('Weighted Tibialis Raise', 'WEIGHT_REPS', true, 'CALVES', 'SPECIALTY', array[]::text[]),
  ('Soleus Raise', 'WEIGHT_REPS', true, 'CALVES', 'SPECIALTY', array[]::text[]),
  ('Hip Airplane', 'BODYWEIGHT_REPS', true, 'GLUTES', 'SPECIALTY', array[]::text[]),
  ('Prone Y-Raise', 'BODYWEIGHT_REPS', true, 'SHOULDERS', 'SPECIALTY', array[]::text[]),
  ('Prone T-Raise', 'BODYWEIGHT_REPS', true, 'SHOULDERS', 'SPECIALTY', array[]::text[]),
  ('Prone W-Raise', 'BODYWEIGHT_REPS', true, 'SHOULDERS', 'SPECIALTY', array[]::text[]),
  ('Serratus Wall Slide', 'BODYWEIGHT_REPS', true, 'SHOULDERS', 'SPECIALTY', array[]::text[]),
  ('Spanish Squat Hold', 'DURATION', true, 'QUADS', 'SPECIALTY', array[]::text[]),
  ('Reverse Sled Drag', 'OTHER', true, 'FULL_BODY', 'SPECIALTY', array[]::text[]),
  ('Neck Flexion', 'WEIGHT_REPS', true, 'NECK', 'SPECIALTY', array[]::text[]),
  ('Neck Extension', 'WEIGHT_REPS', true, 'NECK', 'SPECIALTY', array[]::text[]),
  ('Wrist Curl', 'WEIGHT_REPS', true, 'FOREARMS_GRIP', 'SPECIALTY', array[]::text[]),
  ('Reverse Wrist Curl', 'WEIGHT_REPS', true, 'FOREARMS_GRIP', 'SPECIALTY', array[]::text[]),
  ('Plate Pinch Hold', 'DURATION', true, 'FOREARMS_GRIP', 'SPECIALTY', array[]::text[]),
  ('Grip Trainer Squeeze', 'BODYWEIGHT_REPS', true, 'FOREARMS_GRIP', 'SPECIALTY', array[]::text[])
on conflict (canonical_name) do update
set measurement_type = excluded.measurement_type,
    active = true,
    primary_muscle_group = excluded.primary_muscle_group,
    workout_type = excluded.workout_type,
    aliases = excluded.aliases;

create index if not exists exercise_catalog_active_muscle_name_idx
  on public.exercise_catalog(active, primary_muscle_group, canonical_name);

create index if not exists exercise_catalog_active_type_name_idx
  on public.exercise_catalog(active, workout_type, canonical_name);

create or replace function public.get_exercise_picker_catalog()
returns table (
  id uuid,
  canonical_name text,
  measurement_type text,
  primary_muscle_group text,
  workout_type text,
  aliases text[],
  last_used_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    e.id,
    e.canonical_name,
    e.measurement_type::text,
    e.primary_muscle_group,
    e.workout_type,
    e.aliases,
    recent.last_used_at
  from public.exercise_catalog e
  left join (
    select we.exercise_id, max(w.started_at) as last_used_at
    from public.workout_exercises we
    join public.workout_sessions w on w.id = we.workout_id
    where w.user_id = auth.uid()
      and w.category = 'STRENGTH'
      and w.source = 'IN_APP'
      and w.status = 'COMPLETED'
    group by we.exercise_id
  ) recent on recent.exercise_id = e.id
  where auth.uid() is not null
    and e.active = true
  order by recent.last_used_at desc nulls last, e.canonical_name asc;
$$;

revoke all on function public.get_exercise_picker_catalog() from public, anon, authenticated;
grant execute on function public.get_exercise_picker_catalog() to authenticated;
